/*
  Generated by kissy-xtemplate(kissy pie).*/
KISSY.add( function(){
    return function(scopes,option){
var buffer = "",
S = KISSY,escapeHTML = S.escapeHTML,log = S.log,error = S.error,
commands = option.commands,utils = option.utils,cache=option.cache,eachCommand = commands["each"],withCommand = commands["with"],ifCommand = commands["if"],setCommand = commands["set"],includeCommand = commands["include"],getProperty = utils["getProperty"],subTpls = option.subTpls;
buffer += '<h1>ÖÐÎÄxtemplate</h1>\n';
return buffer;}
});