/*
  Generated by kissy-xtemplate(kissy pie).*/
KISSY.add( function(){
    return function(scopes,option){
var buffer = "",
S = KISSY,escapeHTML = S.escapeHTML,log = S.log,error = S.error,
commands = option.commands,utils = option.utils,cache=option.cache,eachCommand = commands["each"],withCommand = commands["with"],ifCommand = commands["if"],setCommand = commands["set"],includeCommand = commands["include"],getProperty = utils["getProperty"],subTpls = option.subTpls;
buffer += '<h1>\n    文龙 ';
var id0;
var tmp1=getProperty("bar",scopes[0]);
if(tmp1===false){
log("can not find property: 'bar' at line 2", "warn");
id0 = "";
} else {
id0 = tmp1[0];
}
buffer+=escapeHTML(id0);
buffer += '\n</h1>\n';
return buffer;}
});